Fatal error: Uncaught exception 'BadMethodCallException' with message 'Await on a non-Awaitable' in %s:-1
Stack trace:
#0 %s(-1): main()
#1 {main}
